- name: Collect facts
  ansible.builtin.setup:
    filter: ansible_os_family

- name: Distribution
  ansible.builtin.debug:
    msg: "{{ ansible_os_family }}"

- name: Ensure host config dirs
  ansible.builtin.file:
    path: "{{ nginx_host_config_path }}/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0750"
  loop:
    - ssl
    - conf.d

- name: Ensure host log dirs
  ansible.builtin.file:
    path: "{{ nginx_log_dir }}"
    state: directory
    owner: nobody
    setype: httpd_log_t
    group: "{{ 'nobody' if ansible_os_family in ['RedHat', 'RED', 'REDOS', 'Altlinux'] else 'nogroup' }}"
    mode: "0777"

- name: Ensure certificates
  notify: Reload service nginx
  ansible.builtin.copy:
    dest: "{{ nginx_host_config_path }}/ssl/{{ item.name }}"
    content: "{{ item.value }}"
    owner: nobody
    group: "{{ 'nobody' if ansible_os_family in ['RedHat', 'RED', 'REDOS', 'Altlinux'] else 'nogroup' }}"
    mode: "0400"
  loop: "{{ nginx_ssl_certs | flatten(1) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Ensure htpasswd file
  when: nginx_htpasswd_content is defined
  ansible.builtin.copy:
    dest: /etc/nginx/htpasswd
    content: "{{ nginx_htpasswd_content }}"
    owner: nobody
    group: "{{ 'nobody' if ansible_os_family in ['RedHat', 'RED', 'REDOS', 'Altlinux'] else 'nogroup' }}"
    mode: "0640"

- name: Ensure nginx main config
  notify: Reload service nginx
  ansible.builtin.copy:
    dest: "{{ nginx_host_config_path }}/nginx.conf"
    content: "{{ nginx_main_config | default(lookup('file', 'nginx.conf')) }}"
    owner: root
    group: root
    mode: "0644"

- name: Ensure nginx configs
  notify: Reload service nginx
  ansible.builtin.copy:
    dest: "{{ nginx_host_config_path }}/conf.d/{{ item.name }}"
    content: "{{ item.value }}"
    owner: root
    group: root
    mode: "0640"
  loop: "{{ nginx_configs }}"

- name: Remove unmanaged configs
  when: nginx_remove_unmanaged_configs
  block:
    - name: Find files in conf.d dir
      ansible.builtin.find:
        paths: "{{ nginx_host_config_path }}/conf.d"
        patterns: '*.conf'
      register: confd_existing_dir

    - name: Get existing config names
      ansible.builtin.set_fact:
        confd_existing_files: "{% set list = [] %}{% for config in confd_existing_dir.files %}{{ list.append(config.path | basename) }}{% endfor %}{{ list }}"

    - name: Get config names
      ansible.builtin.set_fact:
        confd_files: "{% set list = [] %}{% for config in nginx_configs %}{{ list.append(config.name) }}{% endfor %}{{ list }}"

    - name: Remove unmanaged configs
      ansible.builtin.file:
        path: "{{ nginx_host_config_path }}/conf.d/{{ item }}"
        state: absent
      loop: "{{ confd_existing_files }}"
      when: item not in confd_files
      notify: Reload service nginx

- name: Ensure logrotate config
  when: nginx_log_rotate | length > 0
  ansible.builtin.copy:
    dest: /etc/logrotate.d/nginx_logrotate
    owner: root
    group: root
    mode: "0644"
    content: "{{ nginx_log_rotate }}"

- name: Ensure systemd nginx.service
  notify: Restart service nginx
  ansible.builtin.copy:
    dest: /etc/systemd/system/{{ nginx_service_name }}.service
    mode: "0644"
    content: |
      [Unit]
      Requires=docker.service
      After=docker.service
      StartLimitIntervalSec=0
      [Service]
      ExecStartPre=-/usr/bin/docker rm --force %N
      ExecStart=/usr/bin/docker run \
        --name=%N \
        --rm=true \
      {% if nginx_pull_setting is defined %}
        --pull={{ nginx_pull_setting }} \
      {% endif %}
        --network=host \
        --stop-timeout=300 \
        --label=co.elastic.logs/enabled=true \
        --volume {{ nginx_host_config_path }}/ssl:{{ nginx_docker_config_path }}/ssl:ro \
        --volume {{ nginx_host_config_path }}/conf.d:{{ nginx_docker_config_path }}/conf.d:ro \
        --volume {{ nginx_host_config_path }}/nginx.conf:{{ nginx_docker_config_path }}/nginx.conf:ro \
      {% if nginx_with_prometheus %}
        --volume {{ nginx_host_config_path }}/prometheus:{{ nginx_docker_config_path }}/prometheus:rw \
      {% endif %}
      {% if nginx_additional_mountpoints is defined %}
      {% for mountpoint in nginx_additional_mountpoints %}
        --volume {{ mountpoint }} \
      {% endfor %}
      {% endif %}
        --volume {{ nginx_log_dir }}:/var/log/nginx:rw \
        {{ nginx_docker_repo }}:{{ nginx_docker_image_tag }} {{ nginx_docker_cmd }}
      ExecReload=/usr/bin/docker exec %N nginx -s reload
      Restart=always
      RestartSec=10
      KillMode=process
      [Install]
      WantedBy=multi-user.target

- name: Ensure nginx service started
  ansible.builtin.systemd:
    name: nginx
    daemon_reload: true
    enabled: true
    state: started
